{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "27135b1d-d579-43cf-a2b5-84ba590098fa",
   "metadata": {},
   "outputs": [
    {
     "ename": "IndentationError",
     "evalue": "unindent does not match any outer indentation level (<string>, line 56)",
     "output_type": "error",
     "traceback": [
      "  \u001b[36mFile \u001b[39m\u001b[32m<string>:56\u001b[39m\n\u001b[31m    \u001b[39m\u001b[31mreturn pd.DataFrame(articles)\u001b[39m\n                                 ^\n\u001b[31mIndentationError\u001b[39m\u001b[31m:\u001b[39m unindent does not match any outer indentation level\n"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "import pandas as pd\n",
    "import datetime\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "from wordcloud import WordCloud\n",
    "import os\n",
    "import matplotlib\n",
    "\n",
    "# --- 修改 1: 路徑設定改為相對路徑 ---\n",
    "# 這樣在 GitHub 環境中會直接產生在專案根目錄\n",
    "OUTPUT_DIR = \"data\" \n",
    "if not os.path.exists(OUTPUT_DIR):\n",
    "    os.makedirs(OUTPUT_DIR)\n",
    "\n",
    "KEYWORD = \"保険\"\n",
    "TODAY = datetime.datetime.today().strftime(\"%Y-%m-%d\") # 建議用橫線，網頁顯示較美觀\n",
    "\n",
    "categories = {\n",
    "    \"再保険\": [\"再保険\", \"reinsurance\"],\n",
    "    \"ESG\": [\"ESG\", \"サステナ\", \"気候変動\", \"脱炭素\"],\n",
    "    \"災害リスク\": [\"地震\", \"台風\", \"洪水\", \"豪雨\"],\n",
    "    \"生命保険\": [\"生命保険\", \"生保\"],\n",
    "    \"損害保険\": [\"損保\", \"火災保険\", \"自動車保険\"]\n",
    "}\n",
    "\n",
    "def get_nikkei_news():\n",
    "    url = f\"https://www.nikkei.com/search?keyword={KEYWORD}\"\n",
    "    headers = {\"User-Agent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36\"}\n",
    "    try:\n",
    "        response = requests.get(url, headers=headers)\n",
    "        soup = BeautifulSoup(response.text, \"html.parser\")\n",
    "        articles = []\n",
    "\n",
    "        # 這裡根據日經目前的結構微調抓取邏輯\n",
    "        for a in soup.find_all(\"a\"):\n",
    "            title = a.text.strip()\n",
    "            link = a.get(\"href\")\n",
    "            \n",
    "            if link and link.startswith(\"/\"):\n",
    "                link = \"https://www.nikkei.com\" + link\n",
    "                \n",
    "            if KEYWORD in title and len(title) > 5:\n",
    "                articles.append({\n",
    "                    \"title\": title,\n",
    "                    \"link\": link,\n",
    "                    \"date\": TODAY\n",
    "                })\n",
    "        return pd.DataFrame(articles)\n",
    "    except Exception as e:\n",
    "        print(f\"抓取失敗: {e}\")\n",
    "        return pd.DataFrame()\n",
    "\n",
    "def categorize(title):\n",
    "    for category, keywords in categories.items():\n",
    "        for word in keywords:\n",
    "            if word in title:\n",
    "                return category\n",
    "    return \"その他\"\n",
    "\n",
    "def main():\n",
    "    print(\"🔎 抓取新聞中...\")\n",
    "    df = get_nikkei_news()\n",
    "\n",
    "    if df.empty:\n",
    "        print(\"❌ 沒有抓到資料\")\n",
    "        return\n",
    "\n",
    "    df.drop_duplicates(subset=\"title\", inplace=True)\n",
    "    df[\"category\"] = df[\"title\"].apply(categorize)\n",
    "\n",
    "    # --- 修改 2: 圖表生成加入例外處理 ---\n",
    "    # 這是為了防止 GitHub Actions 因為找不到字體而中斷\n",
    "    try:\n",
    "        # 嘗試設定日文字體，如果失敗就用預設值\n",
    "        matplotlib.rcParams['font.family'] = 'DejaVu Sans' \n",
    "        category_count = df[\"category\"].value_counts()\n",
    "        plt.figure(figsize=(10, 6))\n",
    "        category_count.plot(kind=\"bar\")\n",
    "        plt.title(\"News Distribution\")\n",
    "        plt.tight_layout()\n",
    "        plt.savefig(os.path.join(OUTPUT_DIR, f\"category_distribution.png\"))\n",
    "        plt.close()\n",
    "    except Exception as e:\n",
    "        print(f\"⚠️ 圖表生成跳過: {e}\")\n",
    "\n",
    "    # --- JSON 輸出 (這是網頁運作的核心，不能出錯) ---\n",
    "    json_output = os.path.join(OUTPUT_DIR, \"news_data.json\")\n",
    "    df.to_json(json_output, orient=\"records\", force_ascii=False, indent=4)\n",
    "    \n",
    "    # 同時保留 Excel 備份\n",
    "    output_file = os.path.join(OUTPUT_DIR, f\"insurance_news_{TODAY}.xlsx\")\n",
    "    df.to_excel(output_file, index=False)\n",
    "\n",
    "    print(f\"✅ 分析完成！資料已存至 {json_output}\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c63c1126-2e35-4871-af16-0d996d139051",
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.font_manager as fm\n",
    "for font in fm.findSystemFonts():\n",
    "    print(font)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
